// Generated from ripuli54.vil by util/vil2keymap.py -- do not edit.
// Raw matrix order: rows 0-4 left half, 5-9 right half.

#pragma once

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = {
        {KC_LEFT_BRACKET, KC_1, KC_2, KC_3, KC_4, KC_5},
        {KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T},
        {KC_ESCAPE, KC_A, KC_S, KC_D, KC_F, KC_G},
        {OSM(MOD_LSFT), KC_Z, KC_X, KC_C, KC_V, KC_B},
        {KC_NO, KC_NO, KC_NO, OSL(2), OSL(1), KC_SPACE},
        {KC_MINUS, KC_0, KC_9, KC_8, KC_7, KC_6},
        {KC_BACKSPACE, KC_P, KC_O, KC_I, KC_U, KC_Y},
        {KC_BACKSLASH, KC_RIGHT_BRACKET, KC_L, KC_K, KC_J, KC_H},
        {OSM(MOD_RSFT), KC_SLASH, KC_DOT, KC_COMMA, KC_M, KC_N},
        {KC_NO, KC_NO, KC_NO, OSL(2), OSL(1), KC_ENTER},
    },
    [1] = {
        {KC_GRAVE, KC_TRNS, RALT(KC_2), KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_TRNS, LSFT(KC_1), LSFT(KC_2), LSFT(KC_3), RALT(KC_4), LSFT(KC_5)},
        {KC_TRNS, OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI), OSM(MOD_LSFT), OSM(MOD_RALT)},
        {KC_NONUS_BACKSLASH, LSFT(KC_NONUS_BACKSLASH), RALT(KC_2), RALT(KC_NONUS_BACKSLASH), KC_TRNS, KC_TRNS},
        {KC_NO, KC_NO, KC_NO, TG(9), KC_TRNS, KC_TRNS},
        {KC_EQUAL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {LSFT(KC_MINUS), LSFT(KC_0), LSFT(KC_9), LSFT(KC_8), LSFT(KC_7), LSFT(KC_6)},
        {KC_TRNS, OSM(MOD_RCTL), OSM(MOD_LALT), OSM(MOD_RGUI), OSM(MOD_RSFT), OSM(MOD_RALT)},
        {RALT(KC_MINUS), RALT(KC_0), RALT(KC_9), RALT(KC_8), RALT(KC_7), KC_TRNS},
        {KC_NO, KC_NO, KC_NO, TG(11), KC_TRNS, KC_TRNS},
    },
    [2] = {
        {KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_F12, KC_F11, KC_F10, KC_F9, KC_F8, KC_F7},
        {KC_DELETE, KC_PGUP, KC_END, KC_HOME, KC_NO, KC_NO},
        {KC_INSERT, KC_PAGE_DOWN, KC_RIGHT, KC_UP, KC_DOWN, KC_LEFT},
        {KC_PRINT_SCREEN, KC_NO, KC_VOLU, KC_VOLD, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
    [3] = {
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
    [4] = {
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
    [5] = {
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
    [6] = {
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
    [7] = {
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
    [8] = {
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
        {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    },
#ifdef MIDI_ENABLE
    [9] = {
        {0x7e6b, 0x7e6c, 0x7e6d, 0x7e6e, 0x7e6f, 0x7e70},
        {0x7e4c, 0x7e4d, 0x7e4e, 0x7e4f, 0x7e50, 0x7e51},
        {0x7e46, 0x7e47, 0x7e48, 0x7e49, 0x7e4a, 0x7e4b},
        {0x7e40, 0x7e41, 0x7e42, 0x7e43, 0x7e44, 0x7e45},
        {KC_NO, KC_NO, KC_NO, TO(0), KC_TRNS, KC_TRNS},
        {0x7e76, 0x7e75, 0x7e74, 0x7e73, 0x7e72, 0x7e71},
        {0x7e63, 0x7e62, 0x7e61, 0x7e60, 0x7e5f, 0x7e5e},
        {0x7e5d, 0x7e5c, 0x7e5b, 0x7e5a, 0x7e59, 0x7e58},
        {0x7e57, 0x7e56, 0x7e55, 0x7e54, 0x7e53, 0x7e52},
        {KC_NO, KC_NO, KC_NO, MO(11), KC_TRNS, MO(10)},
    },
    [10] = {
        {0x7e64, 0x7e65, 0x7e66, 0x7e67, 0x7e68, 0x7e69},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 0x7e6a},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
        {KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS},
    },
    [11] = {
        {0x7e04, 0x7e0c, 0x7e0d, 0x7e0f, 0x7e0e, 0x7e07},
        {0x7e04, 0x7e04, 0x7e05, 0x7e06, 0x7e02, 0x7e08},
        {0x7e04, 0x7e04, 0x7e05, 0x7e06, 0x7e02, 0x7e09},
        {0x7e04, 0x7e04, 0x7e05, 0x7e06, 0x7e02, 0x7e00},
        {KC_NO, KC_NO, KC_NO, TO(0), KC_TRNS, 0x7e01},
        {0x7e00, 0x7e0b, 0x7e0a, 0x7e09, 0x7e08, 0x7e07},
        {0x7e00, 0x7e0b, 0x7e0a, 0x7e09, 0x7e08, 0x7e08},
        {0x7e00, 0x7e0b, 0x7e0a, 0x7e09, 0x7e08, 0x7e09},
        {0x7e00, 0x7e0b, 0x7e0a, 0x7e09, 0x7e08, 0x7e00},
        {KC_NO, KC_NO, KC_NO, 0x7e11, 0x7185, 0x7e01},
    },
#endif // MIDI_ENABLE
};
